[package]
authors = ["Machtan <jako3047@gmail.com>"]
name = "kor"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.8"
regex = "0.2.2"
unicode-normalization = "0.1.4"
hangeul2 = { path = "../hangeul2" }
argonaut = { path = "../argonaut" }
